// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6ZYi8ZOHQ5WqUfe4M-0O8VMv5fH02xzI',
    appId: '1:1034503286496:web:3211fd556ba7b613e42a85',
    messagingSenderId: '1034503286496',
    projectId: 'pickle-system',
    authDomain: 'pickle-system.firebaseapp.com',
    storageBucket: 'pickle-system.firebasestorage.app',
    measurementId: 'G-C4TTPHWMCK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdN--7mVSSRty1VKfthjOEVzLGc1h-9ok',
    appId: '1:1034503286496:android:c316de3818787890e42a85',
    messagingSenderId: '1034503286496',
    projectId: 'pickle-system',
    storageBucket: 'pickle-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC59KAER2cSawsklcACx7Z4l2ot4aoF19I',
    appId: '1:1034503286496:ios:00e0527f18c9491fe42a85',
    messagingSenderId: '1034503286496',
    projectId: 'pickle-system',
    storageBucket: 'pickle-system.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC59KAER2cSawsklcACx7Z4l2ot4aoF19I',
    appId: '1:1034503286496:ios:00e0527f18c9491fe42a85',
    messagingSenderId: '1034503286496',
    projectId: 'pickle-system',
    storageBucket: 'pickle-system.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6ZYi8ZOHQ5WqUfe4M-0O8VMv5fH02xzI',
    appId: '1:1034503286496:web:f8ee5335b586a82ae42a85',
    messagingSenderId: '1034503286496',
    projectId: 'pickle-system',
    authDomain: 'pickle-system.firebaseapp.com',
    storageBucket: 'pickle-system.firebasestorage.app',
    measurementId: 'G-LXWH4KLXM2',
  );
}
